// <auto-generated />
using System;
using HomeworkAPI.Data.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HomeworkAPI.Migrations
{
    [DbContext(typeof(HomeworkContext))]
    [Migration("20210429171720_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("HomeworkAPI.Data.Models.Assignment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("assignmentName")
                        .HasColumnType("TEXT");

                    b.Property<string>("grade")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("gradingTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("studentName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("submissionTime")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("HomeworkAPI.Data.Models.Attachment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("assignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("attachmentUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("assignmentId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("HomeworkAPI.Data.Models.Note", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("assignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("note")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("assignmentId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("HomeworkAPI.Data.Models.Attachment", b =>
                {
                    b.HasOne("HomeworkAPI.Data.Models.Assignment", "assignment")
                        .WithMany("attachments")
                        .HasForeignKey("assignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("assignment");
                });

            modelBuilder.Entity("HomeworkAPI.Data.Models.Note", b =>
                {
                    b.HasOne("HomeworkAPI.Data.Models.Assignment", "assignment")
                        .WithMany("notes")
                        .HasForeignKey("assignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("assignment");
                });

            modelBuilder.Entity("HomeworkAPI.Data.Models.Assignment", b =>
                {
                    b.Navigation("attachments");

                    b.Navigation("notes");
                });
#pragma warning restore 612, 618
        }
    }
}
